# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Client1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QMessageBox, QApplication
from chatWindow import MyTableWidget

from testClient import Client as CreateClient
import sys
import threading



class Ui_Form(QWidget):
    def __init__(self, Form, MainWindow):
        super(QWidget, self).__init__(Form)
        self.Form = Form
        self.MainWindow = MainWindow
        Form.setObjectName("Form")
        Form.resize(680, 503)
        self.BenvenueLabel = QtWidgets.QLabel(Form)
        self.BenvenueLabel.setGeometry(QtCore.QRect(30, -10, 661, 161))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.BenvenueLabel.setFont(font)
        self.BenvenueLabel.setObjectName("BenvenueLabel")
        self.ChoiceColor = QtWidgets.QDial(Form)
        self.ChoiceColor.setGeometry(QtCore.QRect(10, 440, 50, 64))
        self.ChoiceColor.setObjectName("ChoiceColor")
        self.PseudoLabel = QtWidgets.QLabel(Form)
        self.PseudoLabel.setGeometry(QtCore.QRect(220, 220, 43, 16))
        self.PseudoLabel.setObjectName("PseudoLabel")
        self.PeudoBox = QtWidgets.QLineEdit(Form)
        self.PeudoBox.setGeometry(QtCore.QRect(260, 220, 113, 20))
        self.PeudoBox.setObjectName("PeudoBox")
        self.IpLabel = QtWidgets.QLabel(Form)
        self.IpLabel.setGeometry(QtCore.QRect(170, 247, 100, 16))
        self.IpLabel.setObjectName("IpLabel")
        self.IpBox = QtWidgets.QLineEdit(Form)
        self.IpBox.setGeometry(QtCore.QRect(260, 247, 113, 20))
        self.IpBox.setObjectName("IpBox")
        self.IpBox.setPlaceholderText('default : 127.0.0.1')
        self.PortLabel = QtWidgets.QLabel(Form)
        self.PortLabel.setGeometry(QtCore.QRect(230, 274, 52, 16))
        self.PortLabel.setObjectName("IpLabel")
        self.PortBox = QtWidgets.QLineEdit(Form)
        self.PortBox.setGeometry(QtCore.QRect(260, 274, 113, 20))
        self.PortBox.setObjectName("PortBox")
        self.PortBox.setPlaceholderText('default : 4444')
        self.RetourButton = QtWidgets.QPushButton(Form)
        self.RetourButton.setGeometry(QtCore.QRect(590, 465, 75, 23))
        self.RetourButton.setObjectName("RetourButton")
        self.RetourButton.clicked.connect(self.retour)
        self.LocalIp = QtWidgets.QLabel(Form)
        self.LocalIp.setGeometry(QtCore.QRect(206, 301, 100, 16))
        self.LocalIp.setObjectName("LocalIp")
        self.LocalBox = QtWidgets.QLineEdit(Form)
        self.LocalBox.setGeometry(QtCore.QRect(260, 301, 113, 20))
        self.LocalBox.setObjectName("LocalBox")
        self.LocalBox.setPlaceholderText('default : 127.0.0.1')
        self.OkButton = QtWidgets.QPushButton(Form)
        self.OkButton.setGeometry(QtCore.QRect(280, 326, 75, 23))
        self.OkButton.setObjectName("OkButton")
        self.OkButton.clicked.connect(self.startClient)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.BenvenueLabel.setText(_translate("Form", "Vueillez choisir un pseudo"))
        self.PseudoLabel.setText(_translate("Form", "Peudo"))
        self.IpLabel.setText(_translate("Form", "Adresse Serveur"))
        self.PortLabel.setText(_translate("Form", "Port"))
        self.RetourButton.setText(_translate("Form", "Retour"))
        self.LocalIp.setText((_translate("Form", "Ip Locale")))
        self.OkButton.setText(_translate("Form", "OK"))

    def retour(self):
        self.Form.hide()
        self.MainWindow.runSecondMainWindow()
        self.MainWindow.show()


    def startClient(self):
        """Mets en place l'affichage du Chat Room"""
        #self.table_widget = MyTableWidget(self.MainWindow)
        #self.MainWindow.setCentralWidget(self.table_widget)

        # on instancie la classe client
        self.Port = self.PortBox.text()
        self.PortBox.clear()

        self.client = CreateClient('192.168.1.165', 6666)
        #int(self.Port)

        # on lance le client
        self.TargetHost = self.IpBox.text()
        self.IpBox.clear()

        """ Mets en place l'affichage du Chat Room """
        self.table_widget = MyTableWidget(self.MainWindow)
        self.MainWindow.setCentralWidget(self.table_widget)

        threadConnect = threading.Thread(target=self.client.connect, args=("192.168.1.165", 6667))
        threadConnect.start()
        #self.client.connect("192.168.1.165", 6667)

        self.Form.hide()
        self.MainWindow.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QMainWindow()
    ui = MyTableWidget(Form)
    Form.setCentralWidget(ui)
    Form.show()
    sys.exit(app.exec_())
