# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from Client1 import Ui_Form as Client1
from PyQt5.QtWidgets import QMessageBox, QMainWindow, QApplication, QWidget
from Server1 import Ui_Form as Server1

from testServer import Server

import sys


class Ui_MainWindow(QWidget):
    def __init__(self, MainWindow):
        super(QWidget, self).__init__()
        self.MainWindow = MainWindow
        print('init secondMainWindow')

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(687, 382)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(50, 9, 50, -1)
        self.gridLayout.setSpacing(9)
        self.gridLayout.setObjectName("gridLayout")
        self.Clientbtn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Anton")
        font.setPointSize(15)
        self.Clientbtn.setFont(font)
        self.Clientbtn.setObjectName("Clientbtn")
        self.Clientbtn.clicked.connect(self.openClient)
        self.gridLayout.addWidget(self.Clientbtn, 1, 0, 1, 1)
        self.Serverbtn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Anton")
        font.setPointSize(15)
        self.Serverbtn.setFont(font)
        self.Serverbtn.setObjectName("Serverbtn")
        self.Serverbtn.clicked.connect(self.openServer)
        self.gridLayout.addWidget(self.Serverbtn, 1, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 687, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Clientbtn.setText(_translate("MainWindow", "Client"))
        self.Serverbtn.setText(_translate("MainWindow", "Server"))
        self.label.setText(_translate("MainWindow", "Choisissez une interface :"))
        #<Set up Client Window>#
        self.Client = QtWidgets.QWidget()
        self.ui_Client = Client1(self.Client, MainWindow)
        #<Set up Server Window>#
        self.Server = QtWidgets.QWidget()
        self.ui_Server = Server1(self.Server, MainWindow)


    def openClient(self):
        self.Client.show()
        self.MainWindow.hide()

    def openServer(self):
        self.Server.show()
        self.MainWindow.hide()


if __name__ == "__main__":
    """import sys
    app = QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())"""
