# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Server1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import threading

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QWidget
from ServerSocket import Server as CreateServer

from chatWindow import MyTableWidget

class Ui_Form(QWidget):
    """partie graphique et lancement du serveur"""
    def __init__(self, Form, MainWindow):
        """Héritage de la superclasse QWidget de PyQt5 + configuration de la fenêtre"""
        super(QWidget, self).__init__(Form)
        self.Form = Form
        self.MainWindow = MainWindow
        Form.setObjectName("Form")
        Form.resize(682, 536)
        self.BienvenueLabel = QtWidgets.QLabel(Form)
        self.BienvenueLabel.setGeometry(QtCore.QRect(10, 0, 1461, 191))
        font = QtGui.QFont()
        font.setPointSize(45)
        self.BienvenueLabel.setFont(font)
        self.BienvenueLabel.setObjectName("BienvenueLabel")
        self.RetourButton = QtWidgets.QPushButton(Form)
        self.RetourButton.setGeometry(QtCore.QRect(590, 500, 75, 23))
        self.RetourButton.setObjectName("RetourButton")
        self.RetourButton.clicked.connect(self.retour)
        self.OkButton = QtWidgets.QPushButton(Form)
        self.OkButton.setGeometry(QtCore.QRect(370, 410, 75, 23))
        self.OkButton.setObjectName("OkButton")
        self.OkButton.clicked.connect(self.startServer)
        self.NomBox = QtWidgets.QLineEdit(Form)
        self.NomBox.setGeometry(QtCore.QRect(270, 240, 121, 21))
        self.NomBox.setObjectName("NomBox")
        self.NomBox.setPlaceholderText('default : admin')
        self.NomLabel = QtWidgets.QLabel(Form)
        self.NomLabel.setGeometry(QtCore.QRect(180, 240, 85, 21))
        self.NomLabel.setObjectName("NomLabel")
        self.PrenomBox_2 = QtWidgets.QLineEdit(Form)
        self.PrenomBox_2.setGeometry(QtCore.QRect(270, 270, 121, 21))
        self.PrenomBox_2.setObjectName("PrenomBox_2")
        self.PrenomBox_2.setPlaceholderText('default : admin')
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(182, 270, 85, 20))
        self.label.setObjectName("label")

        # champs concernant l'ip/port
        self.IpLabel = QtWidgets.QLabel(Form)
        self.IpLabel.setGeometry(QtCore.QRect(196, 300, 63, 16))
        self.IpLabel.setObjectName("IpLabel")
        self.IpBox = QtWidgets.QLineEdit(Form)
        self.IpBox.setGeometry(QtCore.QRect(270, 300, 113, 20))
        self.IpBox.setObjectName("IpBox")
        self.IpBox.setPlaceholderText('default : 127.0.0.1')

        self.PortLabel = QtWidgets.QLabel(Form)
        self.PortLabel.setGeometry(QtCore.QRect(233, 330, 52, 16))
        self.PortLabel.setObjectName("IpLabel")
        self.PortBox = QtWidgets.QLineEdit(Form)
        self.PortBox.setGeometry(QtCore.QRect(270, 330, 113, 20))
        self.PortBox.setObjectName("PortBox")
        self.PortBox.setPlaceholderText('default : 4444')

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        """fonction qui set up valeur des boutons et champs"""
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.BienvenueLabel.setText(_translate("Form", "Bienvenue sur le serveur"))
        self.RetourButton.setText(_translate("Form", "Retour"))
        self.OkButton.setText(_translate("Form", "OK"))
        self.NomLabel.setText(_translate("Form", "Admin Pseudo"))
        self.label.setText(_translate("Form", "Mot de passe"))
        self.IpLabel.setText(_translate("Form", "Adresse Ip"))
        self.PortLabel.setText(_translate("Form", "Port"))

    def retour(self):
        """"fonction executée lorsque l'utilisateur clique sur le bouton 'retour', et
        qui renvoie à la page d'avant (secondMainWindow) """
        self.Form.hide()
        self.MainWindow.runSecondMainWindow()
        self.MainWindow.show()

    def startServer(self):
        """fonction déclanchée par un clique sur le bouton 'ok' et qui lance le serveur
        ainsi que l'interface de Logs du serveur"""

        # debug
        print(self.NomBox.text())
        self.NomBox.clear()
        print(self.PrenomBox_2.text())
        self.PrenomBox_2.clear()

        # récupration de l'ip/port
        self.IpAdresse = self.IpBox.text()
        print('ip : ', self.IpAdresse)
        self.IpBox.clear()
        self.PortUsed = self.PortBox.text()
        print('port : ', self.PortUsed)
        self.PortBox.clear()

        """ Mets en place l'affichage du Chat Room """
        self.table_widget = MyTableWidget(self.MainWindow)
        self.MainWindow.setCentralWidget(self.table_widget)
        self.Form.hide()
        self.MainWindow.show()

        #self.table_widget.lineEdit.setPlaceholderText('test123456789')

        # on instancie et lance le serveur
        self.server = CreateServer(self.IpAdresse, self.PortUsed, self.table_widget)
        #self.IpAdresse, int(self.PortUsed)

        server = threading.Thread(target=self.server.startServer)
        server.start()





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
